#     ContO["ML STAR Tip carrier for 3 Racks with 96 Tips portrait [revision B00]"]: "TIP_CAR_288_B00",
    #     ContO["ML STAR Tip carrier for 3 Racks with 96 Tips portrait [revision C00]"]: "TIP_CAR_288_C00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_HTF_A00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_HTF_B00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_HTF_C00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision A00]"]: "TIP_CAR_288_HT_A00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision B00]"]: "TIP_CAR_288_HT_B00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision C00]"]: "TIP_CAR_288_HT_C00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_LTF_A00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_LTF_B00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_LTF_C00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision A00]"]: "TIP_CAR_288_LT_A00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision B00]"]: "TIP_CAR_288_LT_B00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision C00]"]: "TIP_CAR_288_LT_C00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_STF_A00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_STF_B00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_STF_C00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision A00]"]: "TIP_CAR_288_ST_A00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision B00]"]: "TIP_CAR_288_ST_B00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision C00]"]: " TIP_CAR_288_ST_C00",
    #     ContO["ML STAR Tip carrier with 3 50ul tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_TIP_50ulF_C00",
    #     ContO["ML STAR Tip carrier with 3 50ul tip racks portrait [revision C00]"]: "TIP_CAR_288_TIP_50ul_C00",
    #     ContO["ML STAR Tip carrier with 4 empty tip rack positions landscape, with Barcode Identification [revision A00]"]: "TIP_CAR_384BC_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_HTF_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip racks for 12/16 channel instruments"]: "TIP_CAR_384BC_HT_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_LTF_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip racks for 12/16 channel instruments"]: "TIP_CAR_384BC_LT_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_STF_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_ST_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip with filter racks landscape [revision A00]"]: "TIP_CAR_384BC_TIP_50ulF_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip racks landscape [revision A00]"]: "TIP_CAR_384BC_TIP_50ul_A00",
    #     ContO["ML STAR TIP Carrier for 4 Racks with 96 Tips landscape [revision A00]"]: "TIP_CAR_384_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_HT_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip with filter racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_LTF_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_LT_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments, no barcode identification  [revision A00] "]: "TIP_CAR_384_STF_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip racks for 12/16 channel instruments, no barcode identification  [revision A00]"]: "TIP_CAR_384_ST_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip with filter racks landscape [revision A00]"]: "TIP_CAR_384_TIP_50ulF_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip racks landscape [revision A00]"]: "TIP_CAR_384_TIP_50ul_A00",
    #     ContO["ML STAR Tip Carrier for 5 Racks with 96 Tips landscape [revision A00]"]: "TIP_CAR_480",
    #     ContO["NEST 96 Well Plate"]: "nest_96_wellplate_200ul_flat",
    # #this is for PLATES (C:\Users\Luiza\pylabrobot\pylabrobot\resources\corning_costar\plates.py)
    # #"""" Corning Costar plates """
    #     ContO["Corning Costar 10 ul plate [1536]"]: "Cos_1536_10ul",
    #     ContO["Corning Costar deep well plate [384]"]: "Cos_384_DW",
    #     ContO["Corning Costar PCR plate [384]"]: "Cos_384_PCR",
    #     ContO["ML STAR Tip carrier for 3 Racks with 96 Tips portrait [revision B00]"]: "TIP_CAR_288_B00",
    #     ContO["ML STAR Tip carrier for 3 Racks with 96 Tips portrait [revision C00]"]: "TIP_CAR_288_C00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_HTF_A00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_HTF_B00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_HTF_C00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision A00]"]: "TIP_CAR_288_HT_A00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision B00]"]: "TIP_CAR_288_HT_B00",
    #     ContO["ML STAR Tip carrier with 3 high volume tip racks portrait [revision C00]"]: "TIP_CAR_288_HT_C00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_LTF_A00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_LTF_B00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_LTF_C00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision A00]"]: "TIP_CAR_288_LT_A00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision B00]"]: "TIP_CAR_288_LT_B00",
    #     ContO["ML STAR Tip carrier with 3 low volume tip racks portrait [revision C00]"]: "TIP_CAR_288_LT_C00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision A00]"]: "TIP_CAR_288_STF_A00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision B00]"]: "TIP_CAR_288_STF_B00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_STF_C00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision A00]"]: "TIP_CAR_288_ST_A00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision B00]"]: "TIP_CAR_288_ST_B00",
    #     ContO["ML STAR Tip carrier with 3 standard volume tip racks portrait [revision C00]"]: " TIP_CAR_288_ST_C00",
    #     ContO["ML STAR Tip carrier with 3 50ul tip with filter racks portrait [revision C00]"]: "TIP_CAR_288_TIP_50ulF_C00",
    #     ContO["ML STAR Tip carrier with 3 50ul tip racks portrait [revision C00]"]: "TIP_CAR_288_TIP_50ul_C00",
    #     ContO["ML STAR Tip carrier with 4 empty tip rack positions landscape, with Barcode Identification [revision A00]"]: "TIP_CAR_384BC_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_HTF_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip racks for 12/16 channel instruments"]: "TIP_CAR_384BC_HT_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_LTF_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip racks for 12/16 channel instruments"]: "TIP_CAR_384BC_LT_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_STF_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments"]: "TIP_CAR_384BC_ST_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip with filter racks landscape [revision A00]"]: "TIP_CAR_384BC_TIP_50ulF_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip racks landscape [revision A00]"]: "TIP_CAR_384BC_TIP_50ul_A00",
    #     ContO["ML STAR TIP Carrier for 4 Racks with 96 Tips landscape [revision A00]"]: "TIP_CAR_384_A00",
    #     ContO["ML STAR Tip carrier with 4 high volume tip racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_HT_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip with filter racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_LTF_A00",
    #     ContO["ML STAR Tip carrier with 4 low volume tip racks for 12/16 channel instruments, no barcode identification"]: "TIP_CAR_384_LT_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip with filter racks for 12/16 channel instruments, no barcode identification  [revision A00] "]: "TIP_CAR_384_STF_A00",
    #     ContO["ML STAR Tip carrier with 4 standard volume tip racks for 12/16 channel instruments, no barcode identification  [revision A00]"]: "TIP_CAR_384_ST_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip with filter racks landscape [revision A00]"]: "TIP_CAR_384_TIP_50ulF_A00",
    #     ContO["ML STAR Tip carrier with 4 50ul tip racks landscape [revision A00]"]: "TIP_CAR_384_TIP_50ul_A00",
    #     ContO["ML STAR Tip Carrier for 5 Racks with 96 Tips landscape [revision A00]"]: "TIP_CAR_480",
    #     ContO["NEST 96 Well Plate"]: "nest_96_wellplate_200ul_flat",
    # #this is for PLATES (C:\Users\Luiza\pylabrobot\pylabrobot\resources\corning_costar\plates.py)
    # #"""" Corning Costar plates """
    #     ContO["Corning Costar 10 ul plate [1536]"]: "Cos_1536_10ul",
    #     ContO["Corning Costar deep well plate [384]"]: "Cos_384_DW",
    #     ContO["Corning Costar PCR plate [384]"]: "Cos_384_PCR",
    #     ContO["Corning Costar 2 mL deep well plate [96]"]: "Cos_96_DW_2mL",
    #     ContO["Corning Costar 500ul deep well plate [96]"]: "Cos_96_DW_500ul",
    #     ContO["Corning Costar Half area plate [96]"]: "Cos_96_HalfArea",
    #     ContO["Corning Costar filter plate [96]"]: "Cos_96_Filter",
    #     ContO["Corning Costar PCR plate [96]"]: "Cos_96_PCR",
    #     ContO["Corning Costar ProtCryst plate [96]"]: "Cos_96_ProtCryst",
    #     ContO["Corning Costar SpecOps plate [96]"]: "Cos_96_SpecOps",
    #     ContO["Corning Costar RD plate [96]"]: "Cos_96_Rd",
    #     ContO["Corning Costar UV plate [96]"]: "Cos_96_UV",
    #     ContO["Corning Costar Vb plate [96]"]: "Cos_96_Vb",
    # #this is for TIPRACKS (C:\Users\Luiza\pylabrobot\pylabrobot\resources\corning_costar\plates.py)
    # #""" HAMILTON ML Star tips """
    #     ContO["Tip Rack 24x 4ml Tip with Filter landscape oriented"]: "FourmlTF_L",
    #     ContO["Tip Rack 24x 5ml Tip landscape oriented"]: "FivemlT_L",
    #     ContO["Tip Rack with 96 1000ul High Volume Tip"]: "HT_L",
    #     ContO["Tip Rack with 96 10ul Low Volume Tip with filter"]: "LTF_L",
    #     ContO["Tip Rack with 96 10ul Low Volume Tip"]: "LT_L",
    #     ContO["Tip Rack with 96 300ul Standard Volume Tip with filter"]: "STF_L",
    #     ContO["Tip Rack with 96 300ul Standard Volume Tip"]: "ST_L",
    # #this is for Plate carriers (C:\Users\Luiza\pylabrobot\pylabrobot\resources\corning_costar\plates.py)
    # #""" Hamilton ML Star plate carriers """
    #     ContO["Plate Carrier for 5 deep well 96 Well PCR Plates"]: "PLT_CAR_L5AC_A00",
    #     ContO["Plate Carrier for 5 plates"]: "PLT_CAR_L5AC",
    #     ContO["Plate Carrier with 5 adjustable (height) portrait positions for archive plates"]: "PLT_CAR_L5FLEX_AC",
    #     ContO["Plate Carrier with 5 adjustable (height) positions for MTP"]: "PLT_CAR_L5FLEX_MD",
    #     ContO["Plate Carrier with 5 adjustable (height) positions for MTP "]: "PLT_CAR_L5FLEX_MD_A00",
    #     ContO["Plate Carrier for 5 plates"]: "PLT_CAR_L5MD",
    #     ContO["Plate Carrier for 5 96/384-Well Plates"]: "PLT_CAR_L5MD_A00",
    #     ContO["Plate Carrier for 5 PCR plates"]: "PLT_CAR_L5PCR",
    #     ContO["Plate Carrier for 5 PCR landscape plates [revision 00]"]: "PLT_CAR_L5PCR_A00",
    #     ContO["Plate Carrier for 5 PCR landscape plates [revision 01]"]: "PLT_CAR_L5PCR_A01",
    #     ContO["Plate Carrier for 3 96 Deep Well Plates (portrait)"]: "PLT_CAR_P3AC_A00",
    #     ContO["Plate Carrier for 3 96 Deep Well Plates (portrait) [revision 01]"]: "PLT_CAR_P3AC_A01",
    #     ContO["Plate Carrier PLT_CAR_P3HD"]: "PLT_CAR_P3HD",
    #     ContO["Plate Carrier PLT_CAR_P3MD"]: "PLT_CAR_P3MD",
    #     ContO["Plate Carrier for 3 96/384-Well Plates (Portrait)"]: "PLT_CAR_P3MD_A00",
    #     ContO["Plate Carrier PLT_CAR_P3MD"]: "PLT_CAR_P3MD_A01",
    #     ContO["Carrier for 3 96/384-Well Plates (Portrait)"]: "PLT_CAR_P3MD",
    #     ContO["Plate Carrier PLT_CAR_P3MD"]: "PLT_CAR_P3MD_A01"
    ContO["ML STAR Tip Carrier with 5 4ml tip with filter racks landscape"]: "TIP_CAR_120BC_4mlTF_A00",
